[package]
name = "rocket-web"
version = "0.1.0"
authors = ["Iwan Firmawan <firmawaneiwan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
